### ISSUE TITLE
ES6 syntax is not compiled by Babel

### ISSUE THREAD

**Issue by tinnguyenz** [Shopify/shopify-node-app#103]
Hey guys,

Has anyone configured Babel and Webpack for ES6 compilation? I got this error for arrow fuction:

>ERROR in ./client/components/ApiConsole.js
>Module build failed: SyntaxError: Unexpected token (63:15)

> 61 |   }
>62 | 
> 63 |   valueUpdater = (field) => {
>     |                ^
>  64 |       return (value) => this.setState({[field]: value});
>  65 |     }
>  66 | 

> @ ./client/App.js 17:18-52
> @ ./client/index.js
> @ multi react-hot-loader/patch webpack-hot-middleware/client @shopify/polaris/styles.css >./client/index.js
>webpack: Failed to compile.

**Comment by tinnguyenz** [comment]
I Got this.
Added a Babel plugin in PR [#104](https://github.com/Shopify/shopify-node-app/pull/104) to solve this issue.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
