### ISSUE TITLE
React Input Field - requestFields 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [Shopify/shopify-node-app#107]
Is there an example repo/gist for showing how to use the `requestFields variable` directly with Shopify's API? 

Having an issue accessing the params without the "Request Params" Input Field UI being visible to the user?    

```
 <TextField
            label="Request Params"
            value={requestFields.params}
            onChange={params => dispatch(updateParams(params))}
            multiline={12}
  />
```
Looking to create an input field that updates/edits a specific param within the Request Object above.  

Let me know if this is possible, Cheers!

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
