### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted

### ISSUE THREAD

**Issue by artem-alek** [Shopify/shopify-node-app#109]
After following all the directions and use ngrok. I have the install page showing but after entering my shop url I get a opps something went wrong "Oauth error invalid_request: The redirect_uri is not whitelisted". I am unable to get past the install page. I have checked all my redirect in Shopify partner and all of it is following '{HOST}/shopify/auth/callback'. Anyone else have had issues with this or know what the next step fix is?

**Comment by roeku** [comment]
I just installed it too. It looked like I had a "/" too much in the redirect_uri. 
So instead of { HOST }/auth/shopify/callback it was { HOST }//auth/shopify/callback
If you remove one of the / in the URL the app will install. Not sure where the extra / is coming from yet.

**Comment by vmundhra** [comment]
@artem-alek The Whitelisted redirection URL(s) should be **{ HOST }/auth/shopify/callback** and not **{HOST}/shopify/auth/callback**. Note the 'auth' is before 'shopify' in the url.

**Comment by artem-alek** [comment]
@vmundhra I double checked and added that path too on the whitelist of partners, and still having the issue. I noticed that my web pack is returning /shopify/auth?shop={HOST} and is getting a 304. Not sure what else I can do.

**Comment by leonanluppi** [comment]
Any update about that?

Same issue here

**Comment by leonanluppi** [comment]
@juanpprieto 

I solved this issue on shopify-express package. See: https://github.com/Shopify/shopify-express/pull/82

**Comment by artem-alek** [comment]
@juanpprieto yes my issue was with the .env too. I had the correct address, but I forgot to add `https://` in front of the url. So my `SHOPIFY_APP_HOST` is now `"https://{HOST}"`

**Comment by smudge1307** [comment]
Is the problem that  it should be 'https'  but you use 'http'?

**Comment by smudge1307** [comment]
> After following all the directions and use ngrok. I have the install page showing but after entering my shop url I get a opps something went wrong "Oauth error invalid_request: The redirect_uri is not whitelisted". I am unable to get past the install page. I have checked all my redirect in Shopify partner and all of it is following '{HOST}/shopify/auth/callback'. Anyone else have had issues with this or know what the next step fix is?

Is the problem that it should be 'https' but you use 'http'?

**Comment by smudge1307** [comment]
> @juanpprieto yes my issue was with the .env too. I had the correct address, but I forgot to add `https://` in front of the url. So my `SHOPIFY_APP_HOST` is now `"https://{HOST}"`

Is the problem that it should be 'https' but you use 'http'?

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
