### ISSUE TITLE
main.js not loading

### ISSUE THREAD

**Issue by protonhs** [Shopify/shopify-node-app#113]
Hello, 
I successfully passed all the steps , and when I launched the app, installation went smoothly, everything went well except for the last thing : loading main.js
I see an empty app that nevers fully load in my app page, and in ngrok the ok message never appears : 
GET /assets/main.js                                                                   
GET /                          200 OK     

I attached a screenshot of what I see in the app page, it never fully loads :
<img width="1440" alt="screen shot 2018-04-20 at 10 20 19 am" src="https://user-images.githubusercontent.com/23283374/39043124-801491c2-4484-11e8-86f7-b0e14b074db0.png">

Browser console error : Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH     main.js

Any help please? I've been struggling with this for days!
Thank you in advance.

**Comment by serhatv** [comment]
hi, i have same problem. Did you find any solution?

**Comment by pjatx** [comment]
Happens intermittently for me. If you go back to the app screen and then click the app from the Shopify UI it usually fixes it.

**Comment by gasston** [comment]
Hello ,  i have same problem. Did you find any solution?
thx

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
