### ISSUE TITLE
error-Not Found: The page you were looking for does not exist.

### ISSUE THREAD

**Issue by rucsacman** [Shopify/shopify-node-app#114]
I tried to install app and i got this error how can i fix 
![screenshot from 2018-04-25 11-22-41](https://user-images.githubusercontent.com/28048953/39228409-b104d044-487b-11e8-986d-bc3a45e9b3f2.png)
![screenshot from 2018-04-25 11-24-40](https://user-images.githubusercontent.com/28048953/39228410-b44ba368-487b-11e8-93eb-f95939590b54.png)

**Comment by codepressd** [comment]
Mine looks a little different but a similar error. i got the app installed but when I try to navigate to it I get this page. Any Ideas?
![shopify](https://user-images.githubusercontent.com/15281143/40699385-cf529a9a-6388-11e8-87e9-406b0eb53d15.png)

**Comment by theonlydaleking** [comment]
@codepressd you get this after an uninstall? It'll work if you open in an incognito browser. Looks like something is stored locally that bypasses auth.

**Comment by Nisthar** [comment]
@theonlydaleking I am having the same issues. Any permanent solutions?

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
