### ISSUE TITLE
cant create or get Script tags

### ISSUE THREAD

**Issue by rucsacman** [Shopify/shopify-node-app#115]
I had change scope and try to create script tag but im unable to create script tag 
`action REQUEST_ERROR @ 17:02:57.110
redux-logger.js:1:5935
 prev state 
Object { requestFields: {…}, requestInProgress: true, requestError: null, responseBody: "" }
redux-logger.js:1:6174
 action     
Object { type: "REQUEST_ERROR", payload: {…} }
redux-logger.js:1:6294
 next state 
Object { requestFields: {…}, requestInProgress: false, requestError: SyntaxError, responseBody: "" }`
 How can i fix this.

**Comment by inomn** [comment]
@BrianSullivan425 @rucsacman 
1) You must delete `script_tags` from `DISALLOWED_URLS` in shopify-express package, or you can use my fork with some error fixes:  https://github.com/inomn/shopify-express

2) You must add `read_script_tags, write_script_tags` in `shopifyConfig.scope` in this project ( https://github.com/Shopify/shopify-node-app/blob/master/server/index.js#L31 )

**Comment by daniel-farina** [comment]
fyi to use @inomn  package with his mods: 

npm install git+https://github.com/inomn/shopify-express.git

or in your package.json

```
  "@shopify/shopify-express": "git+https://github.com/inomn/shopify-express.git",
```

then do yarn install (twice)

Thank you @inomn . I tested it and it's working.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
