### ISSUE TITLE
Upgrade to Polaris 2.0

### ISSUE THREAD

**Issue by idiazroncero** [Shopify/shopify-node-app#117]
After banging my head against a lot of errors that came out when trying to use _ResourceList_ and not finding any docs for _EmbeddedApp_ components, I finally realized that I was reading the official Polaris docs (v2.x) while shopify-node-app has remained stuck on v1.8.3. It's easy to get confused...

Is there any plan for upgrading to Polaris 2.x?

**Comment by nilocortex** [comment]
Just encountered the same wall, the components I need are in 2.0.0 but this repo is still on 1.8.3

**Comment by dompenn2010** [comment]
Meh, seems like there's been many more changes than this PR will cover. 

The introduction of the Admin api and much more. 

My apologies but #120 won't do the trick anymore.

**Comment by nemoeric** [comment]
Really weird this topic has not been answered.

Not being able to use Polaris 2.0 makes this entire Shopify-node-app template way less useful ...
I have the exact same issue

**Comment by dompenn2010** [comment]
@nemoeric looks like a Shopify dev seems to think #120 might do the trick after all, they just had me upgrade it to Polaris `2.3.1` so 🤞
