### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by rinkeshclag** [Shopify/shopify-node-app#121]
I have setup app into Shopify. After successful install,  when I click on my app it will show error 404.

![image](https://user-images.githubusercontent.com/39943936/40962141-4f69e024-68c2-11e8-8308-982eb0fef180.png)

Please guide me what step I need to take to fix this bug.

Thanks

**Comment by jfrankdev** [comment]
having the same issue

**Comment by letsbelopez** [comment]
Just started working with this repo. New clone, new app and I'm getting this 404 error.

**Comment by letsbelopez** [comment]
When I had this issue, it was because my App URL was wrong the the app setup page.

**Comment by mitchellporter** [comment]
Had the same issue as @letsbelopez. Made me realize why my previous setup using passportjs was acting strange. I had set the app URL as the initial auth URL.

**Comment by appjitsu** [comment]
yep its what @letsbelopez said above. make sure your app url is correct.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
