### ISSUE TITLE
How can I get Shopify Webhook HMAC?

### ISSUE THREAD

**Issue by weblegend15** [Shopify/shopify-node-app#122]
Hi, hope you are doing well. I am developing the Shopify app using your source code.
I am using webhook on Shopify with this app. so I've added the webhook on Shopify admin and test the webhook.

But it said 
```
Error: Unable to verify request HMAC
    at withWebhook (/Volumes/Data/Work/Shopify/Shopify app/shopify-node-app/node_modules/@shopify/shopify-express/middleware/webhooks.js:21:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
::1 - - [18/Jun/2018:14:37:24 +0000] "POST /order-create HTTP/1.1" 401 - "-" "Ruby"
POST /order-create 401 0.836 ms - -
```

How can I fix it?
Look forward to hearing from you soon

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
