### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by AKarmanov** [Shopify/shopify-node-app#125]
Original clone of repository complains about: 
```upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". (installed node version: 10.6.0)```

The solution is to remove yarn.lock and rebuild but that results in : 
```node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz```

Any ideas on how to fix it?

The issue is with shopify-express dependency.

**Comment by geraintf** [comment]
Having the same problem

**Comment by geraintf** [comment]
I get this issue when pushing to heroku but is fine running locally. My guess would be I have whatever module is being requested locally cached and is failing for any new install.

**Comment by Werbelow** [comment]
Same here, pushed to heroku and had this issue. It shouldn't need sqlite if I am not using that strategy correct?

**Comment by Werbelow** [comment]
I was able to resolve this. I made sure my local and Heroku node versions matched up. Heroku was trying to use some version of 10, which sqlite 3 doesn't seem to work. 

Locally I was using 8.9.1, so I set that same version for Heroku and it all worked :)

**Comment by AKarmanov** [comment]
I ended up updating sqlite version to ^4.x.x in shopify-express module as that was causing my issue. The one used in the module is deprecated.

**Comment by santoshkpragiti** [comment]
Facing Issue on after running **git push heroku master**
Tried after after updat sqlite3 version but still same issue.
Can someone face same issue annd give solution for this.
Below are console logs

 -----> Creating runtime environment

        NPM_CONFIG_LOGLEVEL=error
        NPM_CONFIG_PRODUCTION=true
        YARN_PRODUCTION=true
        NODE_VERBOSE=false
        NODE_ENV=production
        NODE_MODULES_CACHE=true

 -----> Installing binaries
        engines.node (package.json):  >= 8.1.0
        engines.npm (package.json):   unspecified (use default)
        engines.yarn (package.json):  unspecified (use default)

        Resolving node version >= 8.1.0...
        Downloading and installing node 10.7.0...
        Using default npm version: 6.1.0
        Resolving yarn version 1.x...
        Downloading and installing yarn (1.9.2)...
        Installed yarn 1.9.2

 -----> Restoring cache
        Skipping cache restore (not-found)

 -----> Building dependencies
        Installing node modules (yarn.lock)
        yarn install v1.9.2
        [1/4] Resolving packages...
        [2/4] Fetching packages...
        (node:342) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(),
        info fsevents@1.1.3: The platform "linux" is incompatible with this module.
        info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
        [3/4] Linking dependencies...
        warning " > react-object-inspector@0.2.1" has incorrect peer dependency "react@^0.14.0".
        [4/4] Building fresh packages...
        error /tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3: Command failed.
        Exit code: 1
        Command: node-pre-gyp install --fallback-to-build
        Arguments:
        Directory: /tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3
        Output:
        node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
        node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.7.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
        node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
        node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.7.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
        make: Entering directory '/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3/build'
        ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
        make: Entering directory '/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3/build'
        ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
        TOUCH Release/obj.target/deps/action_before_build.stamp
        CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
        TOUCH Release/obj.target/deps/action_before_build.stamp
        CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
        AR(target) Release/obj.target/deps/sqlite3.a
        COPY Release/sqlite3.a
        CXX(target) Release/obj.target/node_sqlite3/src/database.o
        AR(target) Release/obj.target/deps/sqlite3.a
        COPY Release/sqlite3.a
        CXX(target) Release/obj.target/node_sqlite3/src/database.o
        In file included from ../../nan/nan.h:192:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        ../../nan/nan_maybe_43_inl.h: In function `Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAt
        ../../nan/nan_maybe_43_inl.h:112:15: error: `class v8::Object' has no member named `ForceSet'
        return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
        ^
        In file included from ../../nan/nan.h:192:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        ../../nan/nan_maybe_43_inl.h: In function `Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAt
        ../../nan/nan_maybe_43_inl.h:112:15: error: `class v8::Object' has no member named `ForceSet'
        return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:835:60: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::
        v8::Isolate::GetCurrent(), target, func, argc, argv);
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:835:60: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::
        v8::Isolate::GetCurrent(), target, func, argc, argv);
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:850:62: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Va
        v8::Isolate::GetCurrent(), target, symbol, argc, argv);
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:165:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:865:62: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is
        v8::Isolate::GetCurrent(), target, method, argc, argv);
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:158:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:850:62: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Va
        v8::Isolate::GetCurrent(), target, symbol, argc, argv);
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:165:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In function `v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
        ../../nan/nan.h:865:62: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is
        v8::Isolate::GetCurrent(), target, method, argc, argv);
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:158:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In member function `v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
        ../../nan/nan.h:1479:5: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::
        ));
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        In file included from ../src/database.h:10:0,
        from ../src/database.cc:4:
        ../../nan/nan.h: In member function `v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
        ../../nan/nan.h:1479:5: warning: `v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::
        ));
        ^
        In file included from ../../nan/nan.h:49:0,
        from ../src/database.h:10,
        from ../src/database.cc:4:
        /app/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
        NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        ^
        /app/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro `NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)':
        ../src/database.cc:144:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)':
        ../src/database.cc:144:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)':
        ../src/database.cc:230:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)':
        ../src/database.cc:230:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)':
        ../src/database.cc:525:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)':
        ../src/database.cc:625:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)':
        ../src/database.cc:525:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        ../src/database.cc: In static member function `static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)':
        ../src/database.cc:625:9: warning: unused variable `status' [-Wunused-variable]
        int status = uv_queue_work(uv_default_loop(),
        ^
        node_sqlite3.target.mk:115: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
        make: Leaving directory '/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3/build'
        make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
        gypnode_sqlite3.target.mk:115: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
        make: Leaving directory '/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3/build'
        make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
        gyp  ERR! build error
        ERR! build error
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js
        gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
        gyp ERR! System Linux 4.4.0-1019-aws
        gyp ERR! command "/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/bin/node" "/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/lib/node_mod
modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modu
        gypgyp  ERR!ERR!  stackcwd Error: `make` failed with exit code: 2
        /tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3
        gypgyp  ERR!ERR!  stacknode -v v10.7.0
        at ChildProcess.onExit (/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
        gypgyp  ERR!ERR!  stacknode-gyp -v     at ChildProcess.emit (events.js:182:13)
        v3.6.2
        gyp gypERR!  ERR!stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
        not ok
        gyp ERR! System Linux 4.4.0-1019-aws
        gyp ERR! command "/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/bin/node" "/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/lib/node_mod
modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modu
        gyp ERR! cwd /tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3
        gyp ERR! node -v v10.7.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR!node-pre-gyp ERR! build error
        not ok
        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/bin/node /tmp/build_81b459888c04d03a9e30bad88b23
3a9e30bad88b2386e7/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/build_81b459888c04d03a9e30ba
        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
        node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
        node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
        node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
        node-pre-gyp ERR! System Linux 4.4.0-1019-aws
        node-pre-gyp ERR! command "/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/bin/node" "/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sql
        node-pre-gyp ERR! cwd /tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3
        node-pre-gyp ERR! node -v v10.7.0
        node-pre-gyp ERR! node-pre-gyp -v v0.6.39
        node-pre-gyp ERR! not ok
        Failed to execute '/tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/bin/node /tmp/build_81b459888c04d03a9e30bad88b2386e7/.heroku/node/lib/node_modu
/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/build_81b459888c04d03a9e30bad88b2386e7/node_modules/sqlite3
        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 -----> Build failed

        We're sorry this build is failing! You can troubleshoot common issues here:
        https://devcenter.heroku.com/articles/troubleshooting-node-deploys

        Some possible problems:

        - Dangerous semver range (>) in engines.node
        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

        Love,
        Heroku

  !     Push rejected, failed to compile Node.js app.

  !     Push failed
 Verifying deploy...

 !       Push rejected to shopifynodereact.


: Your console font probably doesn't support Unicode. If you experience strange characters in the output, consider switching to a TrueType font such as Consolas!
s://git.heroku.com/shopifynodereact.git
ote rejected] master -> master (pre-receive hook declined)
failed to push some refs to 'https://git.heroku.com/shopifynodereact.git'

**Comment by awhitehouse104** [comment]
Deleting upath from yarn.lock and allowing it to install a newer version worked for me.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
