### ISSUE TITLE
Retrieve Orders and Modify it

### ISSUE THREAD

**Issue by jonatannietoa** [Shopify/shopify-node-app#126]
Hello,

I am using the app to create Tracking numbers of **Orders** that app received through **Orders View**. Now we are selecting N orders and sending it to our app. Now we are using Private App Credentials to get info and modify each order... because I can not retrieve info using App credentials, like this:

<img width="765" alt="captura de pantalla 2018-07-30 a las 12 29 29" src="https://user-images.githubusercontent.com/28530770/43392550-4d32ae8c-93f4-11e8-8f70-fe21b38a5611.png">

how can I do it?

**Comment by vmundhra** [comment]
Hi @jonatannietoa 

were you able to figure this out?

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
