### ISSUE TITLE
 [DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by Noostop** [Shopify/shopify-node-app#127]
C:\Users\YS\Desktop\app>yarn install
yarn install v1.7.0
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ (node:14464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/5] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by BPScott** [comment]
This is deprecation warnings within Yarn when you're using node v10.See this issue https://github.com/yarnpkg/yarn/issues/5477. This is fixed in yarn but not yet released.
