### ISSUE TITLE
Create an authenticated rest api for online store

### ISSUE THREAD

**Issue by vmundhra** [Shopify/shopify-node-app#133]
I want to create an get/post API, that will be called from my store website using App proxy. But I'm not able to extract "**accessToken**" so as to instantiate the shopify-api-node client. The sample code in registerWebhook uses following

```
  const shopify = new ShopifyAPIClient({
    shopName,
    accessToken
  });
```
since it already has the "**accessToken**" from **afterAuth** callback. But if I create a new endpoint, how do I get the token?

```
app.post('/orders', bodyParser.urlencoded({extended: true}), (req, res) => {
  console.log('request received = ', req.body);

  //how to get accessToken???  

  const { session: { shop, accessToken } } = req; // shop = null, accessToken = null
  
  // does not run
  const shopify = new ShopifyAPIClient({
    shopName,
    accessToken
  });

  // create an order
  shopify.order.create({... })
    .then(()=> console.log('order created.'))
    .catch(err => console.error(err));

  res.json(req.body);
});
```

I tried "**withShop**" middleware on the route, as shown in the app on the root route "/" with a Get request, but that doesn't work. Can someone please give an example of creating a rest api? I strongly feel the sample app should provide at-least one rest api example. 

I can possibly declare a global variable for accessToken and then just initialize its value in afterAuth callback once I have the token from session. Is that the only way or is there a cleaner way to extract token and shop variable using a middleware?

**Comment by nemoeric** [comment]
exact same problem !

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
