### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by Nisthar** [Shopify/shopify-node-app#136]
I am getting this error when hosting my app on heroku

It says: 

`Uncaught SyntaxError: Unexpected token < - main.js`

The main.js contains the html instead of javascript. 

I think express is returning the app.ejs file when requesting for main.js file. 

It works in my localhost fine. It returns the contents of main.js file.

Sorry for my bad english.

**Comment by Nisthar** [comment]
Ok, I found the issue. As i expected, heroku is not building the javascript files. I have tried `yarn run build`

It builds the files. But its not storing the build file.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
