### ISSUE TITLE
"One of your dependencies may have a security vulnerability" email

### ISSUE THREAD

**Issue by manmeet-k** [Shopify/shopify-node-app#139]
Hi,

I received an email with this information:

![image](https://user-images.githubusercontent.com/43784447/50785083-8c907480-127d-11e9-8495-ab2d3f0c22f1.png)

![image](https://user-images.githubusercontent.com/43784447/50784972-489d6f80-127d-11e9-88ac-ea8fcc9ad476.png)

Please advise what I need to do.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
