### ISSUE TITLE
README has no reference to SHOPIFY_APP_STORAGE_ENGINE

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify-node-app#43]
README doesn't mention the storage engine options available.

**Comment by TheMallen** [comment]
No longer relevant.

**Comment by jstoeffler** [comment]
Hi. Can I ask why this is no longer relevant? Has this option been removed? Because the value is still declared : https://github.com/Shopify/shopify-node-app/blob/master/.env.example

Should it be removed?
