### ISSUE TITLE
Default scopes separated by a space

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify-node-app#44]
https://jamie-ds-emporium.myshopify.com/admin/oauth/authorize?client_id=199268859c17ed3b6a96570498c52f37&scope=write_orders,%20write_products&redirect_uri=https://jamied.ngrok.io/auth/shopify/callback

`write_orders,%20write_products`

should not contain a space character, scopes should be separated only by commas

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
