### ISSUE TITLE
[shopifyAuth] HMAC validation not sorting URL parameters lexicographically

### ISSUE THREAD

**Issue by devshahani** [Shopify/shopify-node-app#48]
In the `callback` route https://github.com/Shopify/shopify-node-app/blob/master/shopify-express/routes/shopifyAuth.js#L40, the hmac validation process doesn’t follow the same steps listed in our docs (https://help.shopify.com/api/getting-started/authentication/oauth#verification).. Specifically, our docs say `The list of key-value pairs is sorted lexicographically`.
Not doing this doesn’t seem to be an issue where it’s used in this app, but if I copy the code and use it on another request sent by shopify (the one that includes the protocol property), the validation fails

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
