### ISSUE TITLE
hotmodulereloading doesn't seem to work

### ISSUE THREAD

**Issue by devshahani** [Shopify/shopify-node-app#53]
I cloned the project, did `yarn install` and then ran `yarn dev`. 
The Shopify app loads fine in the admin, but I get the following errors in the chrome console: 
> React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.

and 
> [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

> [HMR]  - ./client/App.js

Lmk if there is any other info I can share.

**Comment by TheMallen** [comment]
Could you open a PR for this? :)
