### ISSUE TITLE
yarn displays a warning for the node version

### ISSUE THREAD

**Issue by devshahani** [Shopify/shopify-node-app#54]
When I run the app with `yarn dev` or `yarn run start` the following message is printed in my terminal:
> You are using Node "7.7.3" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"

When trying to set the project up with `dev`, I also got a warning there that this node version wasn't compatible with `dev`.

**Comment by jamiemtdwyer** [comment]
This should be good now that we're on `8.1.0`
