### ISSUE TITLE
⬆️ Bump node version in the `engine` field to 8.9 LTS

### ISSUE THREAD

**Issue by TheMallen** [Shopify/shopify-node-app#61]
We should bump the `engine` field of package.json to the new LTS release.

If we do this we can easily switch a number of our promise invocations to use async / await.

Also nvm won't keep getting mad about my node versions :)

**Comment by kaelig** [comment]
👍 I was just going to suggest the same!

**Comment by msanchez5** [comment]
may i give this a try :) ... all i need to do is remove the engine part of the package.json??

**Comment by Ryan-Gordon** [comment]
Seeing as this is still open I took a crack at it and opened a PR :)

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
