### ISSUE TITLE
Always redirects to Shopify Node App – Installation

### ISSUE THREAD

**Issue by franz-see** [Shopify/shopify-node-app#69]
I tried updating the .env with my data and installed the application on my demo shop. It installs successfully, but everytime I visit the app from the admin screen, it shows the "Shopify Node App – Installation" page. 

From ngrok, I do see that it first tries to access "GET /", and then "GET /assets/main.js" and then "GET /install". 

I was expecting to see the contents of "app.ejs" but somehow, it keeps getting redirected to "install.ejs". Is that really how it's supposed to work? Or is this a bug?  If it's a bug, where can I find clues to resolve this?

**Comment by mundosk8** [comment]
Im facing the same problem. Did you manage how to pass over it?

**Comment by coinpusha** [comment]
I had this issue before.  Make sure your app url in shopify isn't pointing to the /install directory and make sure the url ends with a /.  I hope that helps someone.

**Comment by artem-alek** [comment]
Im having a similar issue but I can't get pass the install page. I keep getting a `Oauth error invalid_request: The redirect_uri is not whitelisted`. I have the proper redirect of `{HOST}/shopify/auth/callback`. Anyone else experience this?

**Comment by leonanluppi** [comment]
@artem-alek  see https://github.com/Shopify/shopify-express/pull/82

**Comment by dan-gamble** [comment]
I'm getting this issue also, whenever i reload because the HMR doesn't seem to work it asks me to install again. Any ideas as to the fix?

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
