### ISSUE TITLE
Webhook example not working

### ISSUE THREAD

**Issue by idiazroncero** [Shopify/shopify-node-app#70]
Hi there, many thanks for your amazing work here;

I'be been trying to wrap my head around webhooks using the provided example. I started by registering a new webhook as follows (I omit less meaningful parts of code with [...], they haven't been changed).

```
const shopifyConfig = {
  host: SHOPIFY_APP_HOST,
  [...]
  afterAuth(request, response) {
    [...]
    registerWebhook(shop, accessToken, {
      topic: 'orders/create',
      address: SHOPIFY_APP_HOST + '/order-create',
      format: 'json'
    });
  },
};
```

And then use the original example (by manually creating an order, setting it to paid in order to move from "drafted" to "created") to no avail. 

```
app.get('/order-create', withWebhook, (request, response) => {
  console.log('We got a webhook!');
  console.log('Details: ', request.webhook);
  console.log('Body:', request.body);
});
````

In the console appears a POST to /order-create with an 404 error as a result. Btw, i'm using yarn run start  to spin everything, ngrok as a tunnel and everything else is working fine - i have even created some routes of my own - so we can assume auth and express.js are working fine.

It sounds strange to me that a POST request is handled by an `app.get` so i changed the code to

```
app.**post**('/order-create', withWebhook, (request, response) => {
  console.log('We got a webhook!');
  console.log('Details: ', request.webhook);
  console.log('Body:', request.body);
});
```

Now is a 500 error; but if i drop the "withWebhook"... I get all the JSON data displayed on my console. 

```
app.post('/order-create', (request, response) => {
  console.log('We got a webhook!');
  console.log('Details: ', request.webhook);
  console.log('Body:', request.body);
});
```

However, deleting the withWebhook feels incorrect and not the way this is supposed to be handled.

Am I missing something?

**Comment by idiazroncero** [comment]
I narrowed it down a little bit;

First, the original [shopify-express repo ](https://github.com/Shopify/shopify-express) uses app.use() instead of app.get().  Still, the error is there.

`````
app.use('/order-create', withWebhook, function(request, response, next) {
  console.log('We got a webhook!');
});
`````

However, if I comment the Error handlers section (in order to prevent them for catching up), an error related with withWebhook middleware arises:

````
ReferenceError: SHOPIFY_APP_SECRET is not defined
    at withWebhook (/Users/idiazroncero/Localdev/otros/shopify-node-app/node_modules/@shopify/shopify-express/middleware/webhooks.js:9:17)
````

It seems that the middleware is unable to access the SHOPIFY_APP_SECRET, which I console.logged to check that is available, as it should be. This prevents any execution and the route is handled by the default case, which returns a 404 and no data.

Why and how the middleware lost access to the app secret is a mistery to me...

**Comment by frankcash** [comment]
I'm also running into this issue.

**Comment by jamiemtdwyer** [comment]
Should be fixed by https://github.com/Shopify/shopify-node-app/pull/80.

**Comment by wuichen** [comment]
when i run the example, im getting this error in the console. 
```
Error creating webhook 'orders/create'. {"errors":{"topic":["Invalid topic specified. Topics allowed: app/uninstalled, collections/create, collections/delete, collections/update, products/create, products/delete, products/update, shop/update"]}}
```

heres the code i use to define the scope 
```
const shopifyConfig = {
  host: SHOPIFY_APP_HOST,
  apiKey: SHOPIFY_APP_KEY,
  secret: SHOPIFY_APP_SECRET,
  scope: ['read_orders', 'write_orders', 'write_products'],
  shopStore: new MemoryStrategy(),
  afterAuth(request, response) {
    const { session: { accessToken, shop } } = request;

    registerWebhook(shop, accessToken, {
      topic: 'orders/create',
      address: `${SHOPIFY_APP_HOST}/order-create`,
      format: 'json'
    });

    return response.redirect('/');
  },
};
```

i have included read_orders, write_orders, write_products in the scope. however, only write products show up when i try to install the local dev app on my development store. the app im trying to build is a sales channel app. am i missing anything?
