### ISSUE TITLE
Problem with script tags

### ISSUE THREAD

**Issue by jballanger** [Shopify/shopify-node-app#71]
Hello,
I'm building an application with shopify-node-app (thanks for your work!) but I can't create any scriptTags and have strange result when I try to read them.

Here is my function client-side : 
```js
export const injectScript = () => {
  return fetch(`/api/script_tags.json`, {
      method: 'POST',
      headers: {
        'Content-type': 'application/json'
      },
      credentials: 'include',
      body: JSON.stringify({
          event: 'onload',
          src: `${window.location.origin}/script/snapcall.js`
      })
    })
    .then(response => response.json())
    .then((json) => {
      console.log(json);
    })
    .catch(error => {
      console.error(error);
    });
};
```

which result in `{"error":"419: unexpected token at 'object Object]'"}`,

so I tried to see what happened in shopify-express (shopifyApiProxy.js) and changed `fetchOptions` to this :
```js
let b = JSON.stringify(body);
const fetchOptions = {
  method,
  b,
  headers: {
    'Content-Type': 'application/json',
    'X-Shopify-Access-Token': accessToken,
  },
};
```

after that I get `{"errors":{"script_tag":"Required parameter missing or invalid"}}`.

Also, when I try to read my scriptTags I get `{"script_tags":[]}`, but if I go to `https://myshop.myshopify.com/admin/script_tags.json`, I get one scriptTag :
```json
{"script_tags":[{"id":8011808800,"src":"\/\/productreviews.shopifycdn.com\/assets\/v4\/spr.js","event":"onload","created_at":"2017-11-03T06:35:03-04:00","updated_at":"2017-11-03T06:35:03-04:00","display_scope":"all","app":"Product Reviews"}]}
```

Am I doing this wrong ?
Thanks.

**Comment by jballanger** [comment]
Ok, so it seems the `GET /admin/script_tags.json` endpoint only return scriptTags of **your** app and not all scriptTags of the shop.

For the POST endpoint, this formatting seems to work well:
```js
return fetch(`/api/script_tags.json`, {
  method: 'POST',
  credentials: 'include',
  body: JSON.stringify({
    "script_tag": {
      "event": "onload",
      "src": "https://myapp.com/script.js"
    }
  })
})
```

Hope this helps.

**Comment by gkrinc** [comment]
Thanks @jballanger! I don't want to say the Shopify API is dumb, but the fact that it can't just accept JSON and has to instead take a string is super lame and caused me hours of frustration.

With EVERY other API I have every worked with I can make a call using `axios`, `fetch` whatever and simply pass in a javascript object as the payload.

Instead with the Shopify API have to `JSON.stringify` the data and set the `Content-type` header to `plain/text` to get things to work. Very odd.
