### ISSUE TITLE
Error in parsing css, in dev environment

### ISSUE THREAD

**Issue by muhammadfaizan** [Shopify/shopify-node-app#73]
running command `npm run dev` throws this error

```

ERROR in ./~/@shopify/polaris/styles.css
Module parse failed: H:\Samples\Shopify\shopify-node-app-master\node_modules\@shopify\polaris\styles.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @-webkit-keyframes Polaris-global--skeletonShimmerAnimation{
|   0%{
|     opacity:0.45; }
 @ multi react-hot-loader/patch webpack-hot-middleware/client @shopify/polaris/styles.css ./client/index.js
```

**Comment by muhammadfaizan** [comment]
I am using windows,
node version `8.9`

**Comment by badoet** [comment]
@AWaselnuk  im encountering the same errors on windows.
Any idea if this is issue on webpack or windows path? or improper environment/tools setup?

**Comment by AWaselnuk** [comment]
I'm not sure off the top of my head so someone will have to investigate further. Thanks so much for raising the issue and letting us know about your OS info!

**Comment by invertedsoftware** [comment]
This happens to me as well:

Debugger listening on ws://127.0.0.1:12662/160ecd3a-168e-4d6b-bd3e-6024f7ccaea9
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:17352) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
express-session deprecated req.secret; provide secret option server\index.js:62:3
webpack built 6779193aafb47979e91b in 3187ms
Version: webpack 2.7.0
Time: 3187ms
  Asset     Size  Chunks                    Chunk Names
main.js  1.99 MB       0  [emitted]  [big]  main

ERROR in ./~/@shopify/polaris/styles.css
Module parse failed: C:\Users\Gal\Downloads\shopify-node-app-master\shopify-node-app-master\node_modules\@shopify\polaris\styles.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @-webkit-keyframes Polaris-global--skeletonShimmerAnimation{
|   0%{
|     opacity:0.45; }
 @ multi react-hot-loader/patch webpack-hot-middleware/client @shopify/polaris/styles.css ./client/index.js
webpack: Failed to compile.

**Comment by IanFergusonZR** [comment]
i see this on windows10, node 8.1 also

kind of seems like a windows issue with the webpack stuff, possibly related to the combination of exclude/include filters on node_modules in the webpack config  - would be great if there is a fix for windows users :) thanks

**Comment by TheMallen** [comment]
Just merged @jbaez001 's PR. Should fix this. Feel free to reopen if it persists.

**Comment by eddyparkinson** [comment]
SHOPIFY_APP_SECRET = undefined
----
I get same error as invertedsoftware 

error:
>  GMT express-session deprecated req.secret; provide secret option at server\index.js:64:3

**adding:**
`console.log('SHOPIFY_APP_SECRET:'+ SHOPIFY_APP_SECRET);
`

**gives:**
SHOPIFY_APP_SECRET:undefined

on Windows 10 with cygwin.
