### ISSUE TITLE
Improve the Polaris component demo with further examples and routing

### ISSUE THREAD

**Issue by AWaselnuk** [Shopify/shopify-node-app#75]
When we shipped https://github.com/Shopify/shopify-node-app/pull/47 we removed the original interface demo (a searchable collection of products using `ResourceList`) for an API console (so meta!).

The API console allows us to demo some basic components and data flow. It also allows us to give people the chance to immediately start interacting with Shopify API endpoints. However, I don't think it does a stellar job of showcasing common Polaris components and UI patterns.

Let's come up with some simple ideas for fleshing out the UI demo and add a router so that app developers can see a more typical set up. As part of this feature it would be good to look at some current popular apps for inspiration.

One simple idea could be to bring back the original product listing idea and then add a link to the API console. That way devs could search products and see `ResourceList` in action > toggle to the API console and `POST` a new product > toggle back and see that new product in the list.

cc @jamiemtdwyer @TheMallen

**Comment by resistorsoftware** [comment]
Or how about this simple one that will surely break a few heads. Add a link in the Admin in say Product Details that when clicked, goes to the App. Show how a route is setup to securely receive said link payload (ie) shop and product ID. Now have that securely authorized request do something with the ID (add, remove a metafield for example) and then redirect the Merchant to an appropriate page. That flexes many aspects of a Node backend, Express, security, routing, and yes, even simple Shopify API calls.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
