### ISSUE TITLE
Annotate the UI code with a focus on teaching Polaris and Redux

### ISSUE THREAD

**Issue by AWaselnuk** [Shopify/shopify-node-app#76]
@jamiemtdwyer pointed out that a lot of developers might not be familiar with Redux. Since this project aims to teach more about Polaris and Redux, I believe a really effective way to do that quickly is to add code comments that explain key parts of the UI.

Rails does a very good job at this when it generates new files and I think we should borrow heavily from them.

We should tackle #75 before this issue.

**Comment by jamiemtdwyer** [comment]
Sounds good! As someone barely literate in Redux/React myself, I'm happy to sanity check :D

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
