### ISSUE TITLE
Unable to get accessToken when deploying to Heroku

### ISSUE THREAD

**Issue by tinnguyenz** [Shopify/shopify-node-app#77]
I got this error when authoring with client store. The app is deployed to Heroku with current repo's configuration:
`2017-12-10T16:35:12.051144+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'accessToken' of undefined
2017-12-10T16:35:12.051267+00:00 app[web.1]: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by julien-mamalian** [comment]
Hello,
Got the same issue !

**Comment by jasenguyen** [comment]
@julien-mamalian Cool. I also asked the author of shopify-express for this issue and this is her answer: https://github.com/Shopify/shopify-express/issues/33
Not figured out the solution yet. Hope to work this out with you 👯‍♂️

**Comment by julien-mamalian** [comment]
This is not complicated to solve it.
When you are in production mode, you need to create a user session for each store with Redis. In the app, the Redis store is not configured and you need to do it.

`const RedisStore = require('connect-redis')(session);
// Add this line on top of index.js
var client = require('redis').createClient(process.env.REDIS_URL);
...
app.use(
  session({
// Add the client in the RedisStore
    store: isDevelopment ? undefined : new RedisStore({client: client}),
    secret: SHOPIFY_APP_SECRET,
    resave: true,
    saveUninitialized: false,
  })
);
`

To find the redis URL, you could use an app such as Redis to Go if you host your app on Heroku. The app will give you an URI that you will have to store in your .env as REDIS_URL. 
And it will work  =)

**Comment by jasenguyen** [comment]
@julien-mamalian That couldn't be any more awesome Julien. With the help of Redis to Go it works absolutely cool <3

**Comment by theptrk** [comment]
I did this and I also set `SHOPIFY_APP_STORAGE_ENGINE` to `redis` in the config variables but I'm still getting a "Request timeout" and 503 on the `GET /auth/shopify/callback...` route

**Comment by agoldis** [comment]
That might be obvious, but on heroku the app runs with `NODE_MODE=production`, that's why this code:

```javascript
app.use(
  session({
    store: isDevelopment ? undefined : new RedisStore(),
    secret: SHOPIFY_APP_SECRET,
    resave: true,
    saveUninitialized: false,
  })
);
```

tries to use (connect-redis)[https://www.npmjs.com/package/connect-redis] which by default is not configured.

For quick development purposes you can just override `store` to be aways `undefined`. Otherwise make sure to have working Redis client.

**Comment by theptrk** [comment]
Yeah I set up redis and used the code from @julien-mamalian and it successfully connects to the redis server but still timeouts on the callback route. I also had to move some dev dependencies into dependencies because of the ‘NODE_ENV’ is production.

**Comment by agoldis** [comment]
@theptrk Just in case... you could use heroku config variables `NPM_CONFIG_PRODUCTION=false` or `YARN_PRODUCTION=false` to prevent pruning dev dependencies

**Comment by sjt-mbed** [comment]
I was deploying on Google App Engine and ran into the same issue. @julien-mamalian solution worked for me. I had to setup an instance on redislabs hosted service following instructions here https://cloud.google.com/community/tutorials/nodejs-redis-on-appengine

My forked code base with associated code changes can be found here https://github.com/sjt-mbed/shopify-node-app/blob/master/server/index.js

**Comment by theptrk** [comment]
@agoldis thanks, i didnt realize NPM_CONFIG_PRODUCTION is an option

**Comment by AntoineGrenier** [comment]
@theptrk That have fixed your issue? I still have the error 503 and Request timeout on Heroku after I change the config variables.

**Comment by Nisthar** [comment]
@julien-mamalian is it possible to use postgres for db storage and redis for sessions?

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
