### ISSUE TITLE
{{  HOST }}/ not allowed as app URL

### ISSUE THREAD

**Issue by abohannon** [Shopify/shopify-node-app#84]
When setting up a new app according to the documentation, Shopify throws an error if the format isn't a valid url `http://domain.com`

Just curious if this is a recent change and/or how are we able to dynamically set the URL for dev stores when using ngrok.

**Comment by MatiasFMolinari** [comment]
I had the same inference. @abohannon did you ever figure out how to setup a dynamic app url so that you can easily switch environments?

**Comment by abohannon** [comment]
@MatiasFMolinari I didn't. I ended up going a different route, but I believe with Ngrok you have to initiate a new local tunnel each time, unless you pay for the fixed tunnel which doesn't change. I've used localtunnel (https://localtunnel.github.io/www/) before and at the time they offered free fixed tunnels, so you might give them a shot.
