### ISSUE TITLE
Can't access app properly on two separate Shopify stores

### ISSUE THREAD

**Issue by deanfields** [Shopify/shopify-node-app#88]
Hi, 

I've been playing around and creating an app with this example. (I'm newish to React/Express) However, I tried installing it on two different Shopify stores at the same time and have come stuck in an issue. Whenever I install the app, it uses the last stores shopOrigin for both Shopify stores. This stops me from being able to open the Resource Picker on the first app. 

This message is shown when I inspect the page (with the problem):

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided (Other store URL) does not match the recipient window's origin (This stores URL)`

I have setup (I believe) Redis to store the session. It seems to overwrite this with the shops URL that last installed the app.

What am I doing wrong? / missing from my app to allow it to work on multiple stores independently?

Opening one of the Shopify stores in a different browser creates two separate 'sess' in redis, and allows them to work.

Thanks!

**Comment by hpawe01** [comment]
Hey @deanfields,

I ran into the same problem and found a solution (see https://github.com/Shopify/shopify-express/issues/60). It still uses the same redis session, but additionally checks, if the shop that performs the request is the same that is stored in the session. Otherwise it restarts the oauth process.

When I apply those changes locally, it works. Hope that helps.

**Comment by deanfields** [comment]
Thanks very much @hpawe01 I will check this out and test it both locally and on Heroku

**Comment by TheMallen** [comment]
Yep this is a bug with `@shopify/express`, if you clear your cookies or use an incognito tab it would also work. 

@hpawe01's solution might end up being used :)

**Comment by youssseeef** [comment]
Has this bug been solved in the current release? I can try to push a PR for it since I'm using both modules in one of my apps.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
