### ISSUE TITLE
Replace webpack config with parceljs

### ISSUE THREAD

**Issue by AWaselnuk** [Shopify/shopify-node-app#94]
[ParcelJS](https://parceljs.org/) offers a zero-config alternative to webpack without giving up any goodies. I've tried it in a personal project and got excellent results.

In the interest of getting things up and running even more quickly for app developers and keeping the bulk of this codebase focused on the Shopify-relevant items, I propose we switch out the webpack config for a parcel set up.

cc @TheMallen

**Comment by TheMallen** [comment]
Yeah I think this is a good choice as well.

**Comment by SeanPrashad** [comment]
Hey everyone - I'm a new contributor and would love to help out with this! I'm new to Parcel but I've done some reading and I think we need to update the `build` command in `package.json` and remove webpack from the package.json and config file.

I'll go ahead and open a PR to get started ✌🏽

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
