### ISSUE TITLE
ShopifyExpress breaking changes (1.0.0-alpha.7)

### ISSUE THREAD

**Issue by BarryCarlyon** [Shopify/shopify-node-app#99]
In package.json

> "@shopify/shopify-express": "^1.0.0-alpha.6",

Installs 1.0.0-alpha.7 as that's currently available.

v.7 appears to have introduced a number of changes that cause this repo to hang and not load at all (until nginx in front of mine, times out).

v.7 also changes the auth/callback URL's. (mostly irrelevant but worth noting)

Since shopify-express is basically "in progress", should shopify-node-app either a) keep up with shopify-express or b) install a known working shopify-express ?

I don't know, otherwise I'd of attached a PR setting 

> "@shopify/shopify-express": "1.0.0-alpha.6",

In package.json

**Comment by dturton** [comment]
same here

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
